services:
  chromium:
    image: mcr.microsoft.com/playwright/python:v1.45.0-jammy
    container_name: caiyun-poc-chromium
    working_dir: /poc
    volumes:
      - ./:/poc
    environment:
      - DISPLAY=:99
    command: tail -f /dev/null
